'use client';

import { useState, useEffect } from "react";
import Navbar from "@/components/Navbar";
import "./globals.css";

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([]);

  useEffect(() => {
    // Obtener carrito (esto depende de cómo lo manejes)
    const storedCart = JSON.parse(localStorage.getItem("cart")) || [];
    setCart(storedCart);
    
  }, []);

  return (
    <html lang="en">
      <body>
        <Navbar cart={cart} />
        <main className="container mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
